<?php

declare(strict_types=1);

$root = dirname(__DIR__);
$source = file_get_contents($root . '/stubs/kumwe_engine.stub.php');
// This deliberately narrow generator admits only the reviewed array-only API.
preg_match_all('/public function ([a-zA-Z]+)\((array \$envelope)?\): array\s*\{\}/', $source, $matches, PREG_SET_ORDER);
if (count($matches) !== 3 || array_column($matches, 1) !== ['capabilities', 'compile', 'execute']) {
    throw new RuntimeException('Review and extend the generator before changing the public stub.');
}
$output = '/* Generated by tools/generate-arginfo.php from stubs/kumwe_engine.stub.php. */' . "\n";
foreach ($matches as $method) {
    $count = isset($method[2]) && $method[2] !== '' ? 1 : 0;
    $output .= "ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_runtime_{$method[1]}, 0, $count, IS_ARRAY, 0)\n";
    if ($count === 1) { $output .= "    ZEND_ARG_TYPE_INFO(0, envelope, IS_ARRAY, 0)\n"; }
    $output .= "ZEND_END_ARG_INFO()\n";
}
$output .= "static const zend_function_entry runtime_methods[] = {\n";
foreach ($matches as $method) {
    $output .= "    PHP_ME(Kumwe_Engine_Runtime, {$method[1]}, arginfo_runtime_{$method[1]}, ZEND_ACC_PUBLIC)\n";
}
$output .= "    PHP_FE_END\n};\n";
$target = $root . '/src/kumwe_engine_arginfo.h';
if (in_array('--check', $argv, true)) {
    if (file_get_contents($target) !== $output) { throw new RuntimeException('Generated arginfo drift.'); }
    echo "Generated arginfo matches the reviewed stub.\n";
} else {
    file_put_contents($target, $output);
}
