<?php

declare(strict_types=1);

$root = dirname(__DIR__);
$source = file_get_contents($root . '/stubs/kumwe_engine.stub.php');
// Admit exactly the reviewed API; unsupported parameter/return combinations
// require a deliberate generator and manifest change.
preg_match_all('/public function ([a-zA-Z]+)\(([^)]*)\): ([a-z]+)\s*\{\}/', $source, $matches, PREG_SET_ORDER);
$expected = [
    ['capabilities', '', 'array'], ['compile', 'array $envelope', 'array'],
    ['execute', 'array $envelope', 'array'], ['release', 'string $planId', 'void'],
];
if (array_map(static fn(array $method): array => array_slice($method, 1), $matches) !== $expected) {
    throw new RuntimeException('Review and extend the generator before changing the public stub.');
}
$output = '/* Generated by tools/generate-arginfo.php from stubs/kumwe_engine.stub.php. */' . "\n";
foreach ($matches as $method) {
    $count = $method[2] !== '' ? 1 : 0;
    $return = $method[3] === 'void' ? 'IS_VOID' : 'IS_ARRAY';
    $output .= "ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_runtime_{$method[1]}, 0, $count, $return, 0)\n";
    if ($count === 1) {
        [$type, $name] = explode(' $', $method[2]);
        $type = $type === 'string' ? 'IS_STRING' : 'IS_ARRAY';
        $output .= "    ZEND_ARG_TYPE_INFO(0, $name, $type, 0)\n";
    }
    $output .= "ZEND_END_ARG_INFO()\n";
}
$output .= "static const zend_function_entry runtime_methods[] = {\n";
foreach ($matches as $method) {
    $output .= "    PHP_ME(Kumwe_Engine_Runtime, {$method[1]}, arginfo_runtime_{$method[1]}, ZEND_ACC_PUBLIC)\n";
}
$output .= "    PHP_FE_END\n};\n";
$target = $root . '/src/kumwe_engine_arginfo.h';
if (in_array('--check', $argv, true)) {
    if (file_get_contents($target) !== $output) { throw new RuntimeException('Generated arginfo drift.'); }
    echo "Generated arginfo matches the reviewed stub.\n";
} else {
    file_put_contents($target, $output);
}
